---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: data
data:
  haproxy.cfg: |
    defaults
        mode tcp
        timeout connect 5s
        timeout client 30s
        timeout server 30s
    frontend redis_front
        bind *:6379
        default_backend redis_back
    backend redis_back
        server redis-node-0 redis-node-0.redis-headless.data.svc.cluster.local:6379 check
        server redis-node-1 redis-node-1.redis-headless.data.svc.cluster.local:6379 check
        server redis-node-2 redis-node-2.redis-headless.data.svc.cluster.local:6379 check
